# Generated by Django 5.0.1 on 2024-02-08 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_yt_id', models.CharField(max_length=11, unique=True)),
                ('s_artist', models.CharField(max_length=99)),
                ('s_title', models.CharField(max_length=99)),
                ('s_album', models.CharField(blank=True, max_length=99, null=True)),
                ('s_released', models.IntegerField()),
                ('s_discovered', models.IntegerField()),
                ('s_comment', models.TextField(blank=True, null=True)),
                ('s_last_updated', models.DateTimeField(auto_now=True)),
                ('s_created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_rank', models.IntegerField()),
                ('r_last_updated', models.DateTimeField(auto_now=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='api.song')),
            ],
        ),
    ]
