# Generated by Django 5.0.1 on 2025-08-09

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models


def migrate_rank_to_rankingentry(apps, schema_editor):
    Ranking = apps.get_model('api', 'Ranking')
    RankingEntry = apps.get_model('api', 'RankingEntry')
    Rank = apps.get_model('api', 'Rank')

    # Create default 'main' ranking
    main, _ = Ranking.objects.get_or_create(slug='main', defaults={'name': 'main'})

    # Move data from Rank to RankingEntry in the 'main' ranking
    for r in Rank.objects.all().select_related('song'):
        RankingEntry.objects.create(ranking=main, song=r.song, r_rank=r.r_rank)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_rank', models.IntegerField()),
                ('r_last_updated', models.DateTimeField(auto_now=True)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.ranking')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.song')),
            ],
            options={'ordering': ['r_rank']},
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('ranking', 'song'), name='u_ranking_song'),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('ranking', 'r_rank'), name='u_ranking_rank'),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.CheckConstraint(check=models.Q(('r_rank__gte', 1)), name='ck_rank_positive'),
        ),
        migrations.RunPython(
            code=migrate_rank_to_rankingentry,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]


